export const routes = {
  Splash: 'Splash',
  SignIn: 'SignIn',
  CreateAccount: 'CreateAccount',
  OnbIdentity: 'OnbIdentity',
  OnbBehavior: 'OnbBehavior',
  OnbPersonality: 'OnbPersonality',
  OnbCollab: 'OnbCollab',
  OnbReveal: 'OnbReveal',
  Home: 'Home',
  Book: 'Book',
  Compatibility: 'Compatibility',
  Vote: 'Vote',
  Explain: 'Explain',
  Personality: 'Personality',
  Telegram: 'Telegram',
  CreateGroup: 'CreateGroup',
  JoinGroup: 'JoinGroup',
  Invite: 'Invite',
  GroupSettings: 'GroupSettings',
  Sync: 'Sync',
  AllScreens: 'AllScreens',
};

export const routeOrder = [
  routes.Splash,
  routes.SignIn,
  routes.CreateAccount,
  routes.OnbIdentity,
  routes.OnbBehavior,
  routes.OnbPersonality,
  routes.OnbCollab,
  routes.OnbReveal,
  routes.Home,
  routes.Book,
  routes.Compatibility,
  routes.Vote,
  routes.Explain,
  routes.Personality,
  routes.Telegram,
  routes.CreateGroup,
  routes.JoinGroup,
  routes.Invite,
  routes.GroupSettings,
  routes.Sync,
];
