export const routes = {
  Splash: 'Splash',
  SignIn: 'SignIn',
  CreateAccount: 'CreateAccount',
  OnbIdentity: 'OnbIdentity',
  OnbBehavior: 'OnbBehavior',
  OnbPersonality: 'OnbPersonality',
  OnbCollab: 'OnbCollab',
  OnbReveal: 'OnbReveal',
  Home: 'Home',
  Book: 'Book',
  Explain: 'Explain',
  Personality: 'Personality',
  CreateGroup: 'CreateGroup',
  JoinGroup: 'JoinGroup',
  GroupDetail: 'GroupDetail',
  GroupPreview: 'GroupPreview',
  Invite: 'Invite',
  GroupSettings: 'GroupSettings',
  Sync: 'Sync',
};

export const routeOrder = [
  routes.Splash,
  routes.SignIn,
  routes.CreateAccount,
  routes.OnbIdentity,
  routes.OnbBehavior,
  routes.OnbPersonality,
  routes.OnbCollab,
  routes.OnbReveal,
  routes.Home,
  routes.Book,
  routes.Explain,
  routes.Personality,
  routes.CreateGroup,
  routes.JoinGroup,
  routes.Invite,
  routes.GroupSettings,
  routes.Sync,
];
